### ISSUE TITLE
Add exercise: No word limit to exercise name

### ISSUE THREAD

**Issue by Jillzyt** [AY2021S1-CS2103-F10-3/tp#184]
Currently, there's no limit to exercise name. It's not shown in UI.

![image](https://user-images.githubusercontent.com/19341717/98104732-d1b17c00-1ed1-11eb-8969-e0ca6649cc09.png)

**Comment by therizhao** [comment]
possible can check if can hover the text

**Comment by Jillzyt** [comment]
![image](https://user-images.githubusercontent.com/19341717/98332878-89619d80-203a-11eb-9f2e-3032fac78a24.png)
![image](https://user-images.githubusercontent.com/19341717/98332913-9bdbd700-203a-11eb-9012-affc113c4c71.png)
