### ISSUE TITLE
Inconsistent messages for addex and editex invalid commands

### ISSUE THREAD

**Issue by Jillzyt** [AY2021S1-CS2103-F10-3/tp#186]
Editex invalid command message: Change INDEX to <index>

![image](https://user-images.githubusercontent.com/19341717/98105149-7d5acc00-1ed2-11eb-914e-d37f39f9737c.png)

![image](https://user-images.githubusercontent.com/19341717/98105167-864b9d80-1ed2-11eb-81e9-72259b609986.png)

**Comment by therizhao** [comment]
standardise -> the second one add \n
