### ISSUE TITLE
Deleteex shows different message when index is 0

### ISSUE THREAD

**Issue by Jillzyt** [AY2021S1-CS2103-F10-3/tp#187]
![image](https://user-images.githubusercontent.com/19341717/98105377-de829f80-1ed2-11eb-988d-2c13fcd28a30.png)

![image](https://user-images.githubusercontent.com/19341717/98105420-ee01e880-1ed2-11eb-8a76-66a9c45d0faf.png)

**Comment by therizhao** [comment]
Message should be the second one
