### ISSUE TITLE
[UG] Command summary not consistent with the format documented above

### ISSUE THREAD

**Issue by Jillzyt** [AY2021S1-CS2103-F10-3/tp#189]
- [x] Edit exercise format different
- [x] Edit exercise format different

- [x] Add format different (comments suppose to be optional)
- [x] Rename [Add, Delete, Edit, Find] to Add Log, Delete Log, Edit Log, Find Log
- [x] Missing help command

**Comment by therizhao** [comment]
## editex
![Screenshot 2020-11-06 at 10 19 24](https://user-images.githubusercontent.com/24352004/98318422-8d30f800-2019-11eb-9fdf-eb4a2b9340b2.png)
![image](https://user-images.githubusercontent.com/24352004/98318392-7be7eb80-2019-11eb-990c-e970be8e8452.png)
- [x] Follow command summary format in UI and docs
- [x] Update e/<exercise> -> exercise name
- [x] verify that all change to correct format (in UI and docs)

## add
![image](https://user-images.githubusercontent.com/24352004/98318698-18aa8900-201a-11eb-9dfb-e237421c899c.png)

- [x] Fix UI format
- [x]  Add one more e.g. with no comments

## Rename
![Screenshot 2020-11-06 at 10 23 48](https://user-images.githubusercontent.com/24352004/98318738-2bbd5900-201a-11eb-8546-92cf2fe73cec.png)

## Missing help command (in cmd summary)
