### ISSUE TITLE
[DG] Update non functional requirements

### ISSUE THREAD

**Issue by Jillzyt** [AY2021S1-CS2103-F10-3/tp#194]
Non-functional requirements in Appendix not updated.

**Comment by therizhao** [comment]
Update: Instructions for manual testing

**Comment by therizhao** [comment]
[ ] must remove more test cases comment
[ ] basic cleanup

**Comment by therizhao** [comment]
![image](https://user-images.githubusercontent.com/24352004/98317990-8fdf1d80-2018-11eb-842e-6f962ef5a1bc.png)
