### ISSUE TITLE
Improve invalid index log output

### ISSUE THREAD

**Issue by therizhao** [AY2021S1-CS2103-F10-3/tp#202]
Current: UI doesn't tell u why it's invalid
<img width="998" alt="Screenshot 2020-11-05 at 18 01 52" src="https://user-images.githubusercontent.com/24352004/98226434-fd476b80-1f90-11eb-90c3-6bfc0d571cad.png">

Expect: UI should say -> Please enter an index found in the logs below

**Comment by Jillzyt** [comment]
Changed it to "Invalid Log index. Please enter an index found in the logs below."
