### ISSUE TITLE
Update User Guide

### ISSUE THREAD

**Issue by therizhao** [AY2021S1-CS2103-F10-3/tp#8]
- [ ]  **Move the draft UG content into the User Guide page** in your repository. Update the content as necessary. If a feature is not implemented in the current version, you can either omit it from the UG or mark it as 'Coming soon' (e.g., `## Archiving contacts [coming soon]`). As mentioned before, while it is more convenient for one person to update the entire UG, we recommend that **each person updates their own part of the docs** so that we can easily track the contribution of each member using [RepoSense](https://nus-cs2103-ay2021s1.github.io/tp-dashboard/#breakdown=true).

**Comment by jeminsieow** [comment]
I don't think this has been completed yet
