### ISSUE TITLE
Do a trial JAR release

### ISSUE THREAD

**Issue by jeminsieow** [AY2021S1-CS2103-F10-3/tp#85]
Do a product release as described in the Developer Guide. You can name it something like v1.2.1 (or v1.3.trial). Ensure that the jar file works as expected in an empty folder and using Java 11, by doing some manual testing. Reason: You are required to do a proper product release for v1.3. Doing a trial at this point will help you iron out any problems in advance. It may take additional effort to get the jar working especially if you use third party libraries or additional assets such as images.

**Comment by therizhao** [comment]
done
