### ISSUE TITLE
Refactor / write tests

### ISSUE THREAD

**Issue by therizhao** [AY2021S1-CS2103-F10-3/tp#97]
Clean up code and write tests

- [ ] Find untested code
- [ ] Add tests

- [ ] Update old tests

**Comment by youaremysky99** [comment]
I will do it

**Comment by therizhao** [comment]
Test added for editexercises

**Comment by therizhao** [comment]
Test was done for addexercises

**Comment by therizhao** [comment]
- [x] delete exercises

**Comment by youaremysky99** [comment]
DeleleEx tests are there.
